"""Weekly investment committee report.

Generates the ten-section memo the brief specifies. Every figure comes from
stored data; where a section cannot be supported by data it says so rather than
producing filler.

The macro section is a deliberate exception, and an important one: this system
has no macroeconomic data feed, so it does **not** write about Egyptian rates,
inflation or FX. It states what it would need instead. Inventing a paragraph
about the macro environment would be exactly the fabrication the whole design
exists to prevent.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from typing import Any, Sequence

from sqlalchemy import desc, func, select
from sqlalchemy.orm import Session

from backend.analytics.service import score_change
from backend.core.config import get_settings
from backend.core.logging_config import EVENT_REPORT, get_logger, log_event
from backend.data.models import (
    Alert,
    Disclosure,
    Portfolio,
    Position,
    PriceBar,
    Report,
    ResearchThesis,
    ScoreHistory,
)
from backend.data.universe import get_universe

logger = get_logger(__name__)


class SyntheticDataRefused(RuntimeError):
    """Raised when a report would be built on synthetic data without acknowledgement."""


@dataclass
class ReportSection:
    key: str
    title: str
    body: str
    data: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {"key": self.key, "title": self.title, "body": self.body, "data": self.data}


@dataclass
class WeeklyReport:
    period_start: date
    period_end: date
    title: str
    sections: list[ReportSection] = field(default_factory=list)
    contains_synthetic: bool = False
    generated_by: str = "deterministic"

    def section(self, key: str) -> ReportSection | None:
        return next((s for s in self.sections if s.key == key), None)

    def to_markdown(self) -> str:
        lines = [f"# {self.title}", ""]
        if self.contains_synthetic:
            lines += [
                "> **⚠ SYNTHETIC DEMONSTRATION DATA**",
                "> Every figure in this report is fictional and corresponds to no real",
                "> security. This report exists to demonstrate the format only.",
                "",
            ]
        lines.append(
            f"*Period: {self.period_start.isoformat()} to {self.period_end.isoformat()} · "
            f"generated {datetime.now(timezone.utc).date().isoformat()} · "
            f"narrative by {self.generated_by}*"
        )
        lines.append("")
        for index, section in enumerate(self.sections, start=1):
            lines.append(f"## {index}. {section.title}")
            lines.append("")
            lines.append(section.body.strip())
            lines.append("")
        lines += [
            "---",
            "",
            "*EGX ALPHA is a personal research tool operating in paper-trading mode. "
            "Its output is generated by software and is not investment advice. Verify "
            "every figure against primary sources before acting on it.*",
        ]
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "contains_synthetic": self.contains_synthetic,
            "generated_by": self.generated_by,
            "sections": [s.to_dict() for s in self.sections],
        }


def _price_on_or_before(session: Session, ticker: str, on: date) -> float | None:
    bar = session.scalar(
        select(PriceBar)
        .where(PriceBar.ticker == ticker.upper(), PriceBar.timestamp <= on)
        .order_by(PriceBar.timestamp.desc())
    )
    if bar is None:
        return None
    return bar.close if bar.close is not None else bar.adjusted_close


def _period_return(
    session: Session, ticker: str, start: date, end: date
) -> float | None:
    first = _price_on_or_before(session, ticker, start)
    last = _price_on_or_before(session, ticker, end)
    if not first or not last or first <= 0:
        return None
    return (last - first) / first


def _pct(value: float | None, digits: int = 2) -> str:
    return "—" if value is None else f"{value:+.{digits}%}"


def _uses_synthetic(session: Session) -> bool:
    return session.scalar(
        select(PriceBar.source).where(PriceBar.source.like("SYNTHETIC%")).limit(1)
    ) is not None


def generate_weekly_report(
    session: Session,
    *,
    as_of: date | None = None,
    acknowledge_synthetic: bool = False,
    persist: bool = True,
) -> WeeklyReport:
    """Build the full ten-section investment committee report."""
    settings = get_settings()
    as_of = as_of or date.today()
    start = as_of - timedelta(days=7)
    synthetic = _uses_synthetic(session)

    if synthetic and not acknowledge_synthetic:
        raise SyntheticDataRefused(
            "This database contains SYNTHETIC DEMONSTRATION DATA. A report built on it "
            "would describe a fictional market. Pass acknowledge_synthetic=True to "
            "generate it for format demonstration only."
        )

    report = WeeklyReport(
        period_start=start,
        period_end=as_of,
        title=f"EGX ALPHA Weekly Investment Committee — {as_of.isoformat()}",
        contains_synthetic=synthetic,
    )

    portfolio = session.scalar(select(Portfolio).order_by(Portfolio.portfolio_id))
    benchmark_return = _period_return(session, settings.benchmark_ticker, start, as_of)

    report.sections.append(_section_executive_summary(session, start, as_of, benchmark_return))
    report.sections.append(_section_performance(session, portfolio, start, as_of, benchmark_return))
    winners, losers = _movers(session, start, as_of)
    report.sections.append(_section_movers("winners", "Biggest Winners", winners, session, start, as_of))
    report.sections.append(_section_movers("losers", "Biggest Losers", losers, session, start, as_of))
    report.sections.append(_section_opportunities(session, as_of))
    report.sections.append(_section_positions(session, portfolio, as_of))
    report.sections.append(_section_thesis_changes(session, as_of))
    report.sections.append(_section_risk(session, portfolio, as_of))
    report.sections.append(_section_macro(session, as_of))
    report.sections.append(_section_next_week(session, as_of))

    if persist:
        record = Report(
            report_type="weekly_committee",
            title=report.title,
            period_start=start,
            period_end=as_of,
            markdown=report.to_markdown(),
            sections=report.to_dict(),
            generated_by=report.generated_by,
            contains_synthetic_data=synthetic,
        )
        session.add(record)
        session.flush()
        log_event(
            logger, EVENT_REPORT, f"Weekly report generated for {as_of}",
            report_id=record.id, synthetic=synthetic,
        )
    return report


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------
def _section_executive_summary(
    session: Session, start: date, end: date, benchmark_return: float | None
) -> ReportSection:
    settings = get_settings()
    universe = get_universe(session, "all")
    returns: list[tuple[str, float]] = []
    for company in universe:
        value = _period_return(session, company.ticker, start, end)
        if value is not None:
            returns.append((company.ticker, value))

    lines: list[str] = []
    if benchmark_return is not None:
        direction = "gained" if benchmark_return > 0 else "declined"
        lines.append(
            f"The {settings.benchmark_ticker} benchmark {direction} "
            f"{abs(benchmark_return):.2%} over the week to {end.isoformat()}."
        )
    else:
        lines.append(
            f"No benchmark price history is stored for {settings.benchmark_ticker}, so "
            "the market's move this week could not be measured."
        )

    if returns:
        advancing = sum(1 for _, r in returns if r > 0)
        breadth = advancing / len(returns)
        average = sum(r for _, r in returns) / len(returns)
        lines.append(
            f"Across the {len(returns)} names with price data, {advancing} advanced and "
            f"{len(returns) - advancing} declined — breadth of {breadth:.0%}. The average "
            f"move was {average:+.2%}."
        )
        # The reading depends on whether breadth agrees with the index direction —
        # a divergence between the two is the informative case.
        if benchmark_return is None:
            lines.append(
                f"Breadth of {breadth:.0%} is recorded, but without a benchmark move "
                "to compare it against it cannot be interpreted."
            )
        elif benchmark_return > 0 and breadth >= 0.6:
            lines.append(
                "The index rose on broad participation: most names advanced, so the "
                "move reflects the market rather than a few large constituents."
            )
        elif benchmark_return > 0 and breadth < 0.5:
            lines.append(
                "The index rose while most names fell. The advance is being carried by "
                "a handful of heavyweights and is not representative of the median EGX "
                "name — a divergence worth watching."
            )
        elif benchmark_return < 0 and breadth >= 0.6:
            lines.append(
                "The index fell while most names advanced. The decline is concentrated "
                "in large constituents rather than broad-based selling, which is a "
                "materially different signal from a market-wide retreat."
            )
        elif benchmark_return < 0 and breadth < 0.4:
            lines.append(
                "The index fell on broad weakness: most names declined, so this was a "
                "market-wide move rather than a few large detractors."
            )
        else:
            lines.append(
                f"Breadth of {breadth:.0%} is broadly consistent with the index move; "
                "participation was mixed with no clear divergence."
            )
    else:
        lines.append(
            "No price data is stored for the universe this week, so market breadth "
            "could not be assessed."
        )

    alerts = session.scalar(
        select(func.count()).select_from(Alert).where(
            Alert.created_at >= datetime(start.year, start.month, start.day)
        )
    ) or 0
    if alerts:
        lines.append(f"{alerts} alert(s) were raised during the period.")

    return ReportSection(
        "executive_summary", "Executive Summary", "\n\n".join(lines),
        {"benchmark_return": benchmark_return, "names_with_data": len(returns)},
    )


def _section_performance(
    session: Session, portfolio: Portfolio | None, start: date, end: date,
    benchmark_return: float | None,
) -> ReportSection:
    if portfolio is None:
        return ReportSection(
            "performance", "Portfolio Performance",
            "No portfolio has been created yet, so there is no performance to report.",
        )

    from backend.portfolio.attribution import analyze_attribution

    attribution = analyze_attribution(session, portfolio, as_of=end)
    periods = attribution.period_returns

    rows = [
        "| Period | Portfolio | Benchmark | Excess |",
        "|---|---:|---:|---:|",
    ]
    for label, key in (("Weekly", "weekly"), ("Monthly", "monthly"),
                       ("Year to date", "ytd")):
        portfolio_value = periods.get(key)
        bench_value = periods.get(f"benchmark_{key}")
        excess = (
            portfolio_value - bench_value
            if portfolio_value is not None and bench_value is not None else None
        )
        rows.append(
            f"| {label} | {_pct(portfolio_value)} | {_pct(bench_value)} | {_pct(excess)} |"
        )
    rows.append(
        f"| Since inception | {_pct(attribution.total_return)} | "
        f"{_pct(attribution.benchmark_return)} | {_pct(attribution.alpha)} |"
    )

    body = [
        f"Portfolio value: **{portfolio.currency} {attribution.portfolio_value:,.0f}** "
        f"against {portfolio.currency} {attribution.initial_capital:,.0f} of initial "
        "capital (paper trading).",
        "",
        "\n".join(rows),
    ]

    if attribution.by_strategy:
        body.append("\n**Contribution by strategy**\n")
        body.append("| Strategy | P&L | Contribution | Positions | Win rate |")
        body.append("|---|---:|---:|---:|---:|")
        for group in attribution.by_strategy:
            win_rate = "—" if group.win_rate is None else f"{group.win_rate:.0%}"
            body.append(
                f"| {group.name} | {portfolio.currency} {group.total_pnl:,.0f} | "
                f"{_pct(group.contribution_to_return, 3)} | {group.position_count} | "
                f"{win_rate} |"
            )
    for note in attribution.notes:
        body.append(f"\n*{note}*")

    return ReportSection(
        "performance", "Portfolio Performance", "\n".join(body),
        {"attribution": attribution.to_dict()},
    )


def _movers(
    session: Session, start: date, end: date, top: int = 5
) -> tuple[list[tuple[str, float]], list[tuple[str, float]]]:
    moves: list[tuple[str, float]] = []
    for company in get_universe(session, "all"):
        value = _period_return(session, company.ticker, start, end)
        if value is not None:
            moves.append((company.ticker, value))
    moves.sort(key=lambda x: -x[1])
    return moves[:top], list(reversed(moves[-top:]))


def _section_movers(
    key: str, title: str, moves: Sequence[tuple[str, float]],
    session: Session, start: date, end: date,
) -> ReportSection:
    if not moves:
        return ReportSection(key, title, "No price data was available for the period.")

    lines = ["| Ticker | Move | Attributed to |", "|---|---:|---|"]
    for ticker, move in moves:
        disclosures = session.execute(
            select(Disclosure)
            .where(
                Disclosure.ticker == ticker,
                Disclosure.date >= start - timedelta(days=7),
                Disclosure.date <= end,
            )
            .order_by(desc(Disclosure.importance))
            .limit(1)
        ).scalars().all()
        # Explain the move only where a disclosure exists. Attributing a price
        # move to an invented cause is exactly the failure this system avoids.
        if disclosures:
            reason = f"{disclosures[0].disclosure_type}: {disclosures[0].title[:80]}"
        else:
            reason = "No disclosure on file for the period — cause not determinable"
        lines.append(f"| **{ticker}** | {move:+.2%} | {reason} |")

    lines.append(
        "\n*Attribution is drawn only from stored disclosures. Where none exists, the "
        "cause of the move is left unexplained rather than guessed at.*"
    )
    return ReportSection(key, title, "\n".join(lines), {"moves": list(moves)})


def _section_opportunities(session: Session, as_of: date, top: int = 5) -> ReportSection:
    latest = (
        select(ScoreHistory.ticker, func.max(ScoreHistory.as_of).label("as_of"))
        .group_by(ScoreHistory.ticker)
        .subquery()
    )
    rows = session.execute(
        select(ScoreHistory)
        .join(
            latest,
            (ScoreHistory.ticker == latest.c.ticker) & (ScoreHistory.as_of == latest.c.as_of),
        )
        .order_by(desc(ScoreHistory.alpha_score))
        .limit(top)
    ).scalars().all()

    if not rows:
        return ReportSection(
            "opportunities", "New Opportunities",
            "No scores have been computed. Run the research pipeline to populate this "
            "section.",
        )

    blocks: list[str] = []
    for row in rows:
        thesis = session.scalar(
            select(ResearchThesis)
            .where(ResearchThesis.ticker == row.ticker)
            .order_by(desc(ResearchThesis.updated_at))
        )
        price = _price_on_or_before(session, row.ticker, as_of)
        lines = [
            f"### {row.ticker} — score {row.alpha_score:.0f}/100"
            if row.alpha_score is not None else f"### {row.ticker}",
            "",
            f"- **Price:** {price:,.2f}" if price else "- **Price:** —",
        ]
        if thesis:
            upside = (
                (thesis.target_price - thesis.entry_price) / thesis.entry_price
                if thesis.target_price and thesis.entry_price else None
            )
            lines += [
                f"- **Strategy:** {thesis.strategy}",
                f"- **Target:** {thesis.target_price:,.2f}" if thesis.target_price else "- **Target:** —",
                f"- **Expected return:** {_pct(upside)}",
                f"- **Invalidation:** {thesis.invalidation_price:,.2f}"
                if thesis.invalidation_price else "- **Invalidation:** —",
                f"- **Conviction:** {thesis.conviction:.1f}/10" if thesis.conviction is not None else "- **Conviction:** —",
                f"- **Holding period:** {thesis.expected_holding_period or '—'}",
            ]
            if thesis.catalysts:
                lines.append("- **Catalysts:** " + "; ".join(
                    str(c.get("title", ""))[:70] for c in thesis.catalysts[:2]
                ))
            if thesis.risks:
                lines.append("- **Risks:** " + "; ".join(str(r)[:90] for r in thesis.risks[:2]))
            if thesis.bear_case:
                first = thesis.bear_case.split("\n")[0]
                lines.append(f"- **Bear case:** {first[:200]}")
        else:
            lines.append("- No thesis has been written for this name yet.")
        blocks.append("\n".join(lines))

    return ReportSection(
        "opportunities", "New Opportunities", "\n\n".join(blocks),
        {"tickers": [r.ticker for r in rows]},
    )


def _section_positions(
    session: Session, portfolio: Portfolio | None, as_of: date
) -> ReportSection:
    if portfolio is None:
        return ReportSection("positions", "Existing Positions", "No portfolio exists.")

    positions = session.execute(
        select(Position).where(Position.portfolio_id == portfolio.portfolio_id)
    ).scalars().all()
    if not positions:
        return ReportSection(
            "positions", "Existing Positions",
            "The portfolio holds no positions. All capital is in cash.",
        )

    lines = ["| Ticker | Weight | P&L | Score | Action | Reasoning |", "|---|---:|---:|---:|---|---|"]
    for position in positions:
        score_row = session.scalar(
            select(ScoreHistory)
            .where(ScoreHistory.ticker == position.ticker, ScoreHistory.as_of <= as_of)
            .order_by(desc(ScoreHistory.as_of))
        )
        score = score_row.alpha_score if score_row else None
        thesis = session.scalar(
            select(ResearchThesis)
            .where(
                ResearchThesis.ticker == position.ticker,
                ResearchThesis.direction == position.direction,
            )
            .order_by(desc(ResearchThesis.updated_at))
        )
        action, reason = _position_action(position, score, thesis, as_of, session)
        pnl = position.unrealized_pnl
        lines.append(
            f"| **{position.ticker}** | "
            f"{(position.portfolio_weight or 0):.1%} | "
            f"{'—' if pnl is None else f'{pnl:,.0f}'} | "
            f"{'—' if score is None else f'{score:.0f}'} | "
            f"**{action}** | {reason} |"
        )
    return ReportSection("positions", "Existing Positions", "\n".join(lines))


def _position_action(
    position: Position, score: float | None, thesis: ResearchThesis | None,
    as_of: date, session: Session,
) -> tuple[str, str]:
    """Decide HOLD / ADD / REDUCE / EXIT for a held position, with a reason."""
    price = position.current_price
    if thesis and thesis.status == "INVALIDATED":
        return "EXIT", "The thesis has been invalidated by price action."
    if thesis and thesis.invalidation_price and price:
        breached = (
            price <= thesis.invalidation_price if position.direction == "LONG"
            else price >= thesis.invalidation_price
        )
        if breached:
            return "EXIT", (
                f"Price {price:,.2f} has breached the invalidation level of "
                f"{thesis.invalidation_price:,.2f}."
            )
    if thesis and thesis.target_price and price:
        reached = (
            price >= thesis.target_price if position.direction == "LONG"
            else price <= thesis.target_price
        )
        if reached:
            return "REDUCE", (
                f"Price {price:,.2f} has reached the {thesis.target_price:,.2f} target. "
                "Take profit or re-underwrite with a higher target."
            )
    if score is None:
        return "HOLD", "No current score — insufficient data to justify a change."
    if score >= 70:
        weight = position.portfolio_weight or 0
        if weight < 0.10:
            return "ADD", f"Score of {score:.0f} supports a larger position than {weight:.1%}."
        return "HOLD", f"Score of {score:.0f} remains strong and the position is already sized."
    if score >= 50:
        return "HOLD", f"Score of {score:.0f} is adequate; the thesis is intact but not improving."
    if score >= 40:
        return "REDUCE", f"Score has fallen to {score:.0f}; trim while reassessing."
    return "EXIT", f"Score of {score:.0f} no longer supports holding the position."


def _section_thesis_changes(session: Session, as_of: date) -> ReportSection:
    theses = session.execute(
        select(ResearchThesis).where(ResearchThesis.version > 1)
        .order_by(desc(ResearchThesis.updated_at)).limit(15)
    ).scalars().all()
    if not theses:
        return ReportSection(
            "thesis_changes", "Thesis Changes",
            "No thesis has been revised yet. Changes appear here from the second "
            "research run onward.",
        )

    blocks: list[str] = []
    for thesis in theses:
        change = score_change(session, thesis.ticker, as_of=as_of, lookback_days=10)
        if change:
            blocks.append(
                f"**{thesis.ticker}** ({thesis.reference}, v{thesis.version})\n\n"
                f"Score: {change['from']:.0f} → {change['to']:.0f} "
                f"({change['delta']:+.0f})\n\n"
                f"Reason: "
                + _explain_change(change)
            )
        elif thesis.versions:
            blocks.append(
                f"**{thesis.ticker}** ({thesis.reference}, v{thesis.version})\n\n"
                f"{thesis.versions[0].change_summary or 'Revised.'}"
            )
    if not blocks:
        return ReportSection(
            "thesis_changes", "Thesis Changes",
            "Theses were revised but no score moved materially week over week.",
        )
    return ReportSection("thesis_changes", "Thesis Changes", "\n\n".join(blocks))


def _explain_change(change: dict[str, Any]) -> str:
    """Explain a score move from its component deltas, not from narrative."""
    components = change.get("components") or {}
    moved = sorted(
        ((k, v) for k, v in components.items() if v is not None and abs(v) >= 1),
        key=lambda kv: -abs(kv[1]),
    )
    if not moved:
        return "component scores were broadly unchanged; the move came from rounding of small shifts."
    parts = [
        f"{name} {'improved' if delta > 0 else 'deteriorated'} by {abs(delta):.0f}"
        for name, delta in moved[:3]
    ]
    return "; ".join(parts) + "."


def _section_risk(
    session: Session, portfolio: Portfolio | None, as_of: date
) -> ReportSection:
    if portfolio is None:
        return ReportSection("risk", "Risk Report", "No portfolio exists.")

    from backend.portfolio.risk import analyze_risk

    report = analyze_risk(session, portfolio, as_of=as_of)
    lines: list[str] = []
    lines.append("| Measure | Value |")
    lines.append("|---|---:|")
    lines.append(f"| Portfolio value | {portfolio.currency} {report.portfolio_value:,.0f} |")
    lines.append(f"| Cash | {_fmt_ratio(report.cash_weight)} |")
    lines.append(f"| Gross exposure | {_fmt_ratio(report.gross_exposure)} |")
    lines.append(f"| Net exposure | {_fmt_ratio(report.net_exposure)} |")
    lines.append(f"| Positions | {report.position_count} |")
    lines.append(f"| Annualised volatility | {_fmt_ratio(report.portfolio_volatility)} |")
    lines.append(f"| Beta vs benchmark | {'—' if report.beta is None else f'{report.beta:.2f}'} |")
    lines.append(f"| Max drawdown | {_fmt_ratio(report.max_drawdown)} |")
    lines.append(f"| Current drawdown | {_fmt_ratio(report.current_drawdown)} |")
    lines.append(f"| Largest position | " + (
        f"{report.largest_position[0]} at {report.largest_position[1]:.1%} |"
        if report.largest_position else "— |"
    ))

    if report.sector_weights:
        lines.append("\n**Sector exposure**\n")
        lines.append("| Sector | Weight |")
        lines.append("|---|---:|")
        for sector, weight in list(report.sector_weights.items())[:8]:
            lines.append(f"| {sector} | {weight:.1%} |")

    if report.warnings:
        lines.append("\n**Limit breaches and warnings**\n")
        for warning in report.warnings:
            icon = {"critical": "⛔", "warning": "⚠", "info": "ℹ"}.get(warning.severity, "•")
            lines.append(f"{icon} **{warning.title}** — {warning.message.splitlines()[0]}")
    else:
        lines.append("\nNo risk limits are currently breached.")

    upcoming = session.execute(
        select(Disclosure)
        .where(Disclosure.date >= as_of - timedelta(days=7), Disclosure.importance >= 4)
        .order_by(desc(Disclosure.date)).limit(5)
    ).scalars().all()
    if upcoming:
        lines.append("\n**Recent material disclosures**\n")
        for row in upcoming:
            lines.append(f"- [{row.date}] {row.ticker}: {row.title[:110]}")

    for note in report.unavailable:
        lines.append(f"\n*{note}*")

    return ReportSection("risk", "Risk Report", "\n".join(lines), {"risk": report.to_dict()})


def _fmt_ratio(value: float | None) -> str:
    return "—" if value is None else f"{value:.1%}"


def _section_macro(session: Session, as_of: date) -> ReportSection:
    """Macro section.

    This system has no macroeconomic data source. Rather than write plausible
    prose about Egyptian rates, inflation and FX — which would be exactly the
    fabrication the architecture is built to prevent — the section states what
    it does not have and what would be needed to fill it.
    """
    body = [
        "**This system has no macroeconomic data feed, so this section reports no "
        "macro figures.**",
        "",
        "Writing about Egyptian policy rates, inflation, the EGP exchange rate, "
        "commodity prices or global market conditions without a data source would "
        "mean inventing them. The architecture forbids that, so the section is left "
        "empty by design rather than filled with plausible prose.",
        "",
        "To populate this section, configure a macro data source covering:",
        "",
        "- Central Bank of Egypt policy rate and inflation prints",
        "- EGP/USD spot and forward rates",
        "- Egyptian sovereign yields and CDS",
        "- Brent crude and Suez Canal traffic (both material to Egypt's external accounts)",
        "- Emerging-market equity flows",
        "",
        "Implement a `MacroDataProvider` alongside the existing provider interfaces in "
        "`backend/data/providers/` and this section will populate automatically.",
    ]

    # What *can* be said from stored data is said.
    settings = get_settings()
    benchmark_1m = _period_return(session, settings.benchmark_ticker, as_of - timedelta(days=30), as_of)
    benchmark_3m = _period_return(session, settings.benchmark_ticker, as_of - timedelta(days=90), as_of)
    if benchmark_1m is not None or benchmark_3m is not None:
        body += [
            "",
            "**What can be measured from stored market data:**",
            "",
            f"- {settings.benchmark_ticker} 1-month: {_pct(benchmark_1m)}",
            f"- {settings.benchmark_ticker} 3-month: {_pct(benchmark_3m)}",
        ]
    return ReportSection("macro", "Macro / EGX Environment", "\n".join(body))


def _section_next_week(session: Session, as_of: date) -> ReportSection:
    lines: list[str] = []

    near_target = session.execute(
        select(ResearchThesis).where(
            ResearchThesis.status.in_(("ACTIVE", "WATCH")),
            ResearchThesis.target_price.isnot(None),
        )
    ).scalars().all()

    watch_items: list[str] = []
    for thesis in near_target:
        price = _price_on_or_before(session, thesis.ticker, as_of)
        if not price or not thesis.target_price or not thesis.invalidation_price:
            continue
        to_target = abs(thesis.target_price - price) / price
        to_invalidation = abs(price - thesis.invalidation_price) / price
        if to_target <= 0.05:
            watch_items.append(
                f"- **{thesis.ticker}** is within {to_target:.1%} of its "
                f"{thesis.target_price:,.2f} target — decide in advance whether to take "
                "profit or re-underwrite."
            )
        elif to_invalidation <= 0.05:
            watch_items.append(
                f"- **{thesis.ticker}** is within {to_invalidation:.1%} of its "
                f"{thesis.invalidation_price:,.2f} invalidation level — the exit "
                "decision may be forced this week."
            )
    if watch_items:
        lines.append("**Positions approaching a decision point**\n")
        lines += watch_items
        lines.append("")

    open_alerts = session.execute(
        select(Alert).where(Alert.status == "NEW", Alert.severity.in_(("critical", "warning")))
        .order_by(desc(Alert.created_at)).limit(6)
    ).scalars().all()
    if open_alerts:
        lines.append("**Unresolved alerts**\n")
        for alert in open_alerts:
            lines.append(f"- [{alert.severity}] {alert.title}")
        lines.append("")

    stale = session.execute(
        select(ResearchThesis)
        .where(ResearchThesis.updated_at <= datetime(as_of.year, as_of.month, as_of.day) - timedelta(days=21))
        .limit(5)
    ).scalars().all()
    if stale:
        lines.append("**Theses not reviewed in over three weeks**\n")
        for thesis in stale:
            lines.append(f"- {thesis.ticker} ({thesis.reference})")
        lines.append("")

    if not lines:
        lines.append(
            "Nothing in the current book is approaching a target, an invalidation "
            "level, or an unresolved alert. The week ahead is a monitoring week."
        )

    lines.append(
        "\n**Standing agenda:** re-run ingestion before the next committee, confirm no "
        "position has drifted through its invalidation level, and check that no sector "
        "has breached its exposure limit."
    )
    return ReportSection("next_week", "Next Week", "\n".join(lines))
